const ED_LIST = [
  { edId: "EC-01", name: "Colombo" },
  { edId: "EC-02", name: "Gampaha" },
  { edId: "EC-03", name: "Kalutara" },
  { edId: "EC-04", name: "Kandy" },
  { edId: "EC-05", name: "Matale" },
  { edId: "EC-06", name: "Nuwara-Eliya" },
  { edId: "EC-07", name: "Galle" },
  { edId: "EC-08", name: "Matara" },
  { edId: "EC-09", name: "Hambantota" },
  { edId: "EC-10", name: "Jaffna" },
  { edId: "EC-11", name: "Vanni" },
  { edId: "EC-12", name: "Batticaloa" },
  { edId: "EC-13", name: "Digamadulla" },
  { edId: "EC-14", name: "Trincomalee" },
  { edId: "EC-15", name: "Kurunegala" },
  { edId: "EC-16", name: "Puttalam" },
  { edId: "EC-17", name: "Anuradhapura" },
  { edId: "EC-18", name: "Polonnaruwa" },
  { edId: "EC-19", name: "Badulla" },
  { edId: "EC-20", name: "Moneragala" },
  { edId: "EC-21", name: "Ratnapura" },
  { edId: "EC-22", name: "Kegalle" },
];
export default ED_LIST;
